### ISSUE TITLE
You cannot put my copyrighted material from Practical Typography under the MIT license

### ISSUE THREAD

**Issue by mbutterick** [kennethwang14/TypographyHandbook#5]
Please either change the license on this project, or remove my material from this repo. Thank you.

**Comment by kennethwang14** [comment]
Hello! Sorry, I wasn't thinking about copyright at all when writing the guide. Would [Unlicense](http://choosealicense.com/licenses/unlicense/) work?

**Comment by mbutterick** [comment]
Obviously (?) no. The Unlicense is even less restrictive than the MIT license. 

Mr. Wang, I don’t want to seem like a jerk. But if you don’t want to “think about” the basic obligations that come with citing copyrighted material, maybe you shouldn’t be using it.

**Comment by kennethwang14** [comment]
Sorry again! Removed your material from the repo. If everything is good, I'll close the Issue!
