### ISSUE TITLE
Polling github API too often

### ISSUE THREAD

**Issue by r12a** [kennethwang14/TypographyHandbook#6]
I had this page open but minimised in my browser for several days while i waited for a good time to read it.  During that time it was repeatedly using the github API and draining my rate-limit, which was badly affecting my use of other pages that populate the page with content using the github API.  Finally, the helpful folks at github helped me identify this page as the culprit.

I suggest you only use an API call once when the page is opened.

**Comment by kennethwang14** [comment]
Thank you for bringing this issue to my attention. I have switched to another GitHub starring service that only polls the API a single time.
