### ISSUE TITLE
Add white background to body

### ISSUE THREAD

**Issue by charakterziffer** [kennethwang14/TypographyHandbook#7]
There are browser themes that don’t have a default white background for websites. For example Firefox on Ubuntu prefers showing a light grey for website bodies when the web designer didn’t define the background. This results in seeing white shadows behind all links in the Typography Handbook.

![typo-handbook](https://cloud.githubusercontent.com/assets/7194876/16169890/4b414054-353f-11e6-8046-1b4cd258fa12.png)

To prevent this, explicitly define body {background-color: white;}.

**Comment by kennethwang14** [comment]
This should be fixed in the latest version which is now live. Thanks for the bug report!
